# Generated by Django 6.0.6 on 2026-06-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('device_type', models.CharField(choices=[('Router', 'Core Router'), ('Switch', 'L2/L3 Switch'), ('Access Point', 'Wireless AP / Bridge'), ('Server', 'Bare Metal Server')], default='Switch', max_length=50)),
                ('status', models.CharField(default='Unknown', max_length=10)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
