# Generated by Django 6.0.6 on 2026-06-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netpulse_Engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='health_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='temperature_c',
            field=models.FloatField(default=40.0),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='update_required',
            field=models.BooleanField(default=False),
        ),
    ]
