# Generated by Django 6.0.6 on 2026-07-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netpulse_Engine', '0002_networkdevice_health_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='health_score',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='temperature_c',
            field=models.FloatField(blank=True, default=40.0, null=True),
        ),
    ]
